version: '3.8'

services:
  mongo:
    image: mongo
    container_name: surfforecast-mongo
    restart: always
    ports:
      - "27017:27017"

  test:
    build: .
    entrypoint: yarn test
    environment:
      - MONGO_URI=mongodb://mongo:27017/surf-forecast
    volumes:
      - .:/surfforecast
      - /surfforecast/node_modules
    depends_on:
     - mongo
    links:
      - mongo

  surfforecast-api:
    build: .
    entrypoint: yarn start
    container_name: surfforecast-api
    volumes:
      - .:/surfforecast
    environment:
      - MONGO_URI=mongodb://mongo:27017/surf-forecast
    depends_on:
      - mongo
    ports:
      - "3000:3000"