name: Release

on:
  push:
      branches: [ master ]

jobs:
  deploy_stg:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    environment: 
      name: staging
      url: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com
    steps:
      - uses: actions/checkout@v2
    
      - name: Login to Heroku Container registry
        run: heroku container:login
        
      - name: Build and push
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web 
        
      - name: Release
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web 

  deploy_prd:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    environment: 
      name: production
      url: https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com
    steps:
      - uses: actions/checkout@v2
    
      - name: Login to Heroku Container registry
        run: heroku container:login
        
      - name: Build and push
        run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web 
        
      - name: Release
        run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web 